- name: Install rust
  include_role:
    name: asdf
  vars:
    asdf_skip_update: True
    asdf_plugins:
      - name: "rust"
        repository: "https://github.com/asdf-community/asdf-rust.git"
        versions:
          - "latest"
        global: "latest"
