- name: check if cargo is installed
  command: cargo -v
  register: cargo_exists
  become_user: "{{ username }}"
  ignore_errors: yes

- name: Install Rust
  when: cargo_exists is failed
  block:
    - name: Download Installer
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup.sh

    - name: Run Installer
      command: sudo sh /tmp/rustup.sh --no-modify-path -y

- name: Update Rust
  when: cargo_exists is successful
  become_user: "{{ username }}"
  command: rustup update stable
