- name: Install golang
  include_role:
    name: asdf
  vars:
    asdf_skip_update: True
    asdf_plugins:
      - name: "golang"
        repository: "https://github.com/asdf-community/asdf-golang.git"
        versions:
          - "latest"
        global: "latest"
