- name: Download Installer
  get_url:
    url: https://cdn.coollabs.io/coolify/install.sh
    owner: "{{ username }}"
    mode: "u+rx"
    dest: /tmp/coolify.sh

- name: Run Installer
  command: /tmp/coolify.sh

- name: Stop coolify containers every day at 4:40 AM
  cron:
    name: "Stop coolify containers every day at 4:40 AM"
    minute: "40"
    hour: "4"
    job: "docker stop $(docker container ls -q -f 'name=coolify*')"

- name: Start coolify containers every day at 5:00 AM
  cron:
    name: "Start coolify containers every day at 5:00 AM"
    minute: "0"
    hour: "5"
    job: "docker start $(docker ps -q -f 'status=exited')"
