- include_vars: backup.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/rclone"

- name: Copy the config file
  copy:
    src: files/paperless.conf
    dest: "{{ docker_dir }}/{{ container_name }}/rclone/rclone.conf"
    decrypt: yes
    owner: "root"
    group: "root"

- name: Make sure the {{ container_name }}-backup container is created
  community.docker.docker_container:
    name: "{{ container_name }}-backup"
    image: "guergeiro/iac-backup:latest"
    pull: yes
    state: "present"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
      "PG_HOST": "{{ paperless_backup_dbhost }}"
      "PG_DBNAME": "{{ paperless_backup_dbname }}"
      "PG_USERNAME": "{{ paperless_backup_dbuser }}"
      "PG_PASSWORD": "{{ paperless_backup_dbpass }}"
      "ZIP_PASSWORD": "{{ zip_password }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/rclone:/.config/rclone"
      - "{{ docker_dir }}/{{ container_name }}/media:/media"
    networks:
      - name: docker_network
    restart_policy: "on-failure"
    command: "paperless"

- name: Backup {{ container_name }} at 4:30 AM
  cron:
    name: "Backup {{ container_name }} at 4:30 AM"
    minute: "30"
    hour: "4"
    job: "docker start {{ container_name }}-backup"
