container_name: "wireguard"
hostname_vpn: "vpn.{{ base_hostname }}"
host_port:
  - "51820:51820/udp"

post_up: "iptables -t nat -A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE -m comment --comment 'wg-easy-rule'; iptables -A INPUT -p udp -m udp --dport 51820 -j ACCEPT -m comment --comment 'wg-easy-rule'; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT -m comment --comment 'wg-easy-rule';"
pre_down: "iptables-save | grep -vF 'wg-easy rule' | iptables-restore"
