- hosts: localhost
  become: yes
  pre_tasks:
    - import_tasks: tasks/system.yml

  roles:
    - role: system
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: docker
    - role: dotfiles
    - role: tmux
    - role: asdf
    - role: rust
    - role: deno
    - role: java
    - role: kotlin
    - role: golang
    - role: pnpm
    - role: alacritty
    - role: prompt
    - role: neovim
