- hosts: localhost
  become: yes

  roles:
    - role: system
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.docker
      vars:
        docker_apt_repository: "deb [arch={{ docker_apt_arch }} signed-by=/etc/apt/trusted.gpg.d/docker.asc] {{ docker_repo_url }}/{{ docker_apt_ansible_distribution | lower }} {{ lookup('ini', 'UBUNTU_CODENAME type=properties file=/etc/os-release') if ansible_distribution in ['Pop!_OS', 'Linux Mint'] else ansible_distribution_release }} {{ docker_apt_release_channel }}"
    - role: docker
    - role: dotfiles
    - role: tmux
    - role: rust
    - role: deno
    - role: sdkman
    - role: golang
    - role: pnpm
    - role: alacritty
    - role: prompt
    - role: neovim
