- hosts: lisbon
  gather_facts: no
  pre_tasks:
    - import_tasks: tasks/ssh_juggle.yml

- hosts: lisbon
  become: yes

  roles:
    - role: system
    - role: users
    - role: geerlingguy.security
    - role: geerlingguy.ntp
    - role: geerlingguy.git
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: docker
    - role: security
    - role: cloudflare
    - role: traefik
    - role: wireguard
    - role: postgres
    - role: vaultwarden
    - role: paperless
    - role: homeassistant
    - role: freshrss
