---
collections:
  - name: ansible.posix
  - name: community.general
  - name: community.docker
  - name: community.postgresql
roles:
  - name: geerlingguy.security
  - name: geerlingguy.ntp
  - name: geerlingguy.docker
