- name: Set amd64 arch
  set_fact:
    repo_arch: amd64
  when: ansible_facts['architecture'] == "x86_64"

- name: Set base family id
  set_fact:
    lsb_base_id: Ubuntu
  when: ansible_facts['lsb']['id'] in ['Ubuntu', 'Linuxmint']

- name: Set base ubuntu family codename (20.x based distros)
  set_fact:
    lsb_base_codename: focal
  when: ansible_facts['lsb']['codename'] in ['focal', 'ulyana', 'ulyssa', 'uma', 'una']

- name: Set base ubuntu family codename (22.x based distros)
  set_fact:
    lsb_base_codename: jammy
  when: ansible_facts['lsb']['codename'] in ['jammy', 'vanessa', 'vera']
