---
- name: SSH Port Juggle | define the fallback SSH port
  set_fact:
    _fallback_ssh_port: "22"

- name: SSH User Juggle | define the fallback SSH user
  set_fact:
    _fallback_ssh_user: "root"

- name: SSH Port Juggle | save the original SSH port
  set_fact:
    _original_ssh_port: "{{ ansible_port }}"

- name: SSH User Juggle | save the original SSH user
  set_fact:
    _original_ssh_user: "{{ ansible_user }}"

- name: SSH Juggle
  include_tasks:
    file: tasks/ssh_attempt.yml
    apply:
      when: _ssh_condition|d(true)
  with_items:
    - { port: "{{ _original_ssh_port }}", user: "{{ _original_ssh_user }}" }
    - { port: "{{ _fallback_ssh_port }}", user: "{{ _original_ssh_user }}" }
    - { port: "{{ _original_ssh_port }}", user: "{{ _fallback_ssh_user }}" }
    - { port: "{{ _fallback_ssh_port }}", user: "{{ _fallback_ssh_user }}" }


- name: SSH Juggle | Fail
  fail: msg="Neither the configured ansible_port and ansible_user nor the fallback port and user were reachable"
  when: _ssh_condition|d(true)
