- include_vars: dotfiles.yml

- name: Create the directory
  become_user: "{{ username }}"
  file:
    state: directory
    path: "{{ clone_directory }}"
    recurse: yes

- name: Clone repository
  become_user: "{{ username }}"
  ignore_errors: yes # if repo is not clean, sometimes I wait to commit changes
  git:
    repo: "git@github.com:Guergeiro/dotfiles.git"
    dest: "{{ clone_directory }}"

- name: Install stow
  package:
    name: "stow"
    state: present

- name: Undo stow
  command: "stow --target $HOME --delete {{ item }}"
  become_user: "{{ username }}"
  args:
    chdir: "{{ base_directory }}/guergeiro/dotfiles"
  with_items: "{{ stow_directories }}"

- name: Remove default .bashrc
  become_user: "{{ username }}"
  file:
    path: "$HOME/.bashrc"
    state: absent

- name: Run stow
  command: "stow --target $HOME --stow {{ item }}"
  become_user: "{{ username }}"
  args:
    chdir: "{{ base_directory }}/guergeiro/dotfiles"
  with_items: "{{ stow_directories }}"
