hostname: "{{ inventory_hostname }}"
timezone: "Europe/Lisbon"
ntp_timezone: "{{ timezone }}"
locale: "en_US.UTF-8"
keyboard_layout: "us"
username: "breno"
uid: "1000"
ansible_distribution: "{{ 'Ubuntu' if ansible_distribution in ['Pop!_OS', 'Linux Mint'] else ansible_distribution }}"
