- name: Ubuntu specific tasks
  when: ansible_facts['lsb']['id'] == "Ubuntu"
  block:
    - name: Remove cloud-config to avoid boot delay
      apt:
        name: cloud-config
        state: absent

- name: Update and upgrade apt packages
  when: ansible_facts['os_family'] == "Debian"
  block:
    - name: apt-get update
      apt:
        update_cache: yes

    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: apt-get upgrade
      apt:
        upgrade: yes

    - name: apt-get dist-upgrade
      apt:
        upgrade: dist

    - name: apt-get dist-upgrade
      apt:
        upgrade: dist

    - name: apt-get autoclean
      apt:
        autoclean: yes

    - name: apt-get autoremove
      apt:
        autoremove: yes
        purge: true

- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['lsb']['id'] }}.yml"

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: homeserver tasks
  when: ansible_facts['hostname'] != "localhost"
  block:
    - name: Set the hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Reboot every day at 4:50 AM
      cron:
        name: "Reboot every day at 4:50 AM"
        minute: "50"
        hour: "4"
        job: "/sbin/reboot"
