- name: Ubuntu specific tasks
  when: ansible_facts['lsb']['id'] == "Ubuntu"
  block:
    - name: Remove cloud-config to avoid boot delay
      apt:
        name: cloud-config
        state: absent

- name: Update and upgrade apt packages
  when: ansible_facts['os_family'] == "Debian"
  apt:
    upgrade: yes
    autoremove: yes
    force_apt_get: yes
    update_cache: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['lsb']['id'] }}.yml"

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: homeserver tasks
  when: ansible_facts['hostname'] != "localhost"
  block:
    - name: Set the hostname
      hostname:
        name: "{{ inventory_hostname }}"

    - name: Reboot every day at 4:50 AM
      cron:
        name: "Reboot every day at 4:50 AM"
        minute: "50"
        hour: "4"
        job: "/sbin/reboot"
