- name: Ubuntu specific tasks
  become: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  block:
    - name: Remove cloud-config to avoid boot delay
      apt:
        name: cloud-config
        state: absent

- name: Update and upgrade apt packages (Debian and Ubuntu)
  when: ansible_os_family == "Debian"
  apt:
    upgrade: yes
    autoremove: yes
    force_apt_get: yes
    update_cache: yes

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Include OS-specific variables
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Shut down every day at 4:30 AM
  cron:
    name: "Power off at night to save energy"
    minute: "30"
    hour: "4"
    job: "/sbin/reboot"
