- name: Remove old binary
  become_user: "{{ username }}"
  file:
    path: "$ASDF_HOME/bin"
    state: absent

- name: Create folders
  become_user: "{{ username }}"
  file:
    path: "$ASDF_HOME/bin"
    state: directory
    recurse: yes

- name: Install annoyingly unpackaged python module requirement
  pip:
    name: github3.py
    state: present

- name: Find latest release
  community.general.github_release:
    user: "asdf-vm"
    repo: "asdf"
    action: latest_release
  register: release_data

- name: Remove annoyingly unpackaged python module requirement
  pip:
    name: github3.py
    state: absent

- name: Download binary
  become_user: "{{ username }}"
  unarchive:
    src: "https://github.com/asdf-vm/asdf/releases/latest/download/asdf-{{ release_data.tag }}-linux-amd64.tar.gz"
    dest: "$ASDF_HOME/bin"
    remote_src: yes
