- include_vars: asdf.yml

- name: Install asdf plugins
  become_user: "{{ username }}"
  shell: >-
    $ASDF_HOME/bin/asdf plugin add {{ item.name }} {{ item.repository }}
  environment: "{{ environment_variables }}"
  with_items: "{{ asdf_plugins }}"

- name: Install asdf packages
  become_user: "{{ username }}"
  shell: >-
    $ASDF_HOME/bin/asdf install {{ item.0.name }} {{ item.1 }}
  environment: "{{ environment_variables }}"
  ignore_errors: true
  with_subelements:
    - "{{ asdf_plugins }}"
    - versions
    - flags:
      skip_missing: True

- name: Set global asdf packages
  become_user: "{{ username }}"
  shell: >-
    $ASDF_HOME/bin/asdf set --home {{ item.name }} {{ item.global }}
  environment: "{{ environment_variables }}"
  when: item.global is defined
  with_items: "{{ asdf_plugins }}"

- name: Reshim asdf packages
  become_user: "{{ username }}"
  shell: >-
    $ASDF_HOME/bin/asdf reshim
  environment: "{{ environment_variables }}"
