- include_vars: cloudflare.yml

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "favonia/cloudflare-ddns:latest"
    pull: yes
    state: "started"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
      "CF_API_TOKEN": "{{ cloudflare_dns_token }}"
      "PROXIED": "true"
      "DOMAINS": "{{ ','.join(domains) }}"
      "UPDATE_CRON": "{{ cron }}"
    network_mode: "host"
    restart_policy: always
