- include_vars: nginx.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
    mode: 0644
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/data"
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "jc21/nginx-proxy-manager:latest"
    pull: yes
    state: "started"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
    ports: "{{ host_port }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt:/etc/letsencrypt"
    networks:
      - name: docker_network
    purge_networks: yes
    restart_policy: always
