- include_vars: freshrss.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/data"
      - "{{ docker_dir }}/{{ container_name }}/extensions"
      - "{{ docker_dir }}/{{ container_name }}/git-extensions"

- name: Clone repositories
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.directory }}"
    single_branch: yes
  with_items:
    - {
        directory: "{{ docker_dir }}/{{ container_name }}/git-extensions/Extensions",
        url: "https://github.com/FreshRSS/Extensions.git",
      }
    - {
        directory: "{{ docker_dir }}/{{ container_name }}/git-extensions/RedditImage",
        url: "https://github.com/aledeg/xExtension-RedditImage.git",
      }
    - {
        directory: "{{ docker_dir }}/{{ container_name }}/git-extensions/RedditSub",
        url: "https://github.com/balthisar/xExtension-RedditSub.git",
      }
    - {
        directory: "{{ docker_dir }}/{{ container_name }}/git-extensions/AutoTheme",
        url: "https://github.com/aidistan/freshrss-extensions.git",
      }

- name: Copy selected extensions
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ docker_dir }}/{{ container_name }}/extensions/"
    remote_src: true
  with_items:
    - "{{ docker_dir }}/{{ container_name }}/git-extensions/Extensions/xExtension-ReadingTime"
    - "{{ docker_dir }}/{{ container_name }}/git-extensions/RedditImage"
    - "{{ docker_dir }}/{{ container_name }}/git-extensions/RedditSub"
    - "{{ docker_dir }}/{{ container_name }}/git-extensions/AutoTheme/xExtension-ThemeModeSynchronizer"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "freshrss/freshrss:latest"
    pull: yes
    state: "started"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
      "CRON_MIN": "0,15,30,45"
      "LISTEN": "0.0.0.0:8080"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/var/www/FreshRSS/data"
      - "{{ docker_dir }}/{{ container_name }}/extensions:/var/www/FreshRSS/extensions"
    networks:
      - name: docker_network
    purge_networks: yes
    restart_policy: always

- name: Start {{ container_name }} at 5:00 AM
  cron:
    name: "Start {{ container_name }} at 5:00 AM"
    minute: "0"
    hour: "5"
    job: "docker start {{ container_name }}"
