electricty_vazio_meter_reading:
  name: Electricty Vazio Meter Reading
  mode: box
  unit_of_measurement: kWh
  min: 0
  max: 99999999
  step: 1
  icon: mdi:transmission-tower
electricty_ponta_meter_reading_medium:
  name: Electricty Ponta Meter Reading
  mode: box
  unit_of_measurement: kWh
  min: 0
  max: 99999999
  step: 1
  icon: mdi:transmission-tower
electricty_cheia_meter_reading_medium:
  name: Electricty Cheia Meter Reading
  mode: box
  unit_of_measurement: kWh
  min: 0
  max: 99999999
  step: 1
  icon: mdi:transmission-tower
water_meter_reading:
  name: Water Meter Reading
  mode: box
  unit_of_measurement: m3
  min: 0
  max: 9999
  step: 0.001
  icon: mdi:water
gas_meter_reading:
  name: Gas Meter Reading
  mode: box
  unit_of_measurement: m3
  min: 0
  max: 99999
  step: 0.001
  icon: mdi:fire
