- name: Make sure "{{ username }}" user is created
  user:
    append: yes
    expires: -1
    groups: sudo
    name: "{{ username }}"
    # https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_filters.html#id36
    password: "{{ user_password | string | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string, rounds=5002) }}"
    shell: /bin/bash
    uid: "{{ uid }}"

- name: Set authorized_key for "{{ username }}"
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', ansible_ssh_private_key_file ~ '.pub') }}"
