- name: Make sure "{{ username }}" user is created
  user:
    append: yes
    expires: -1
    groups: sudo
    name: "{{ username }}"
    password: "{{ user_hashed_password }}"
    shell: /bin/bash
    uid: "{{ uid }}"

- name: Set authorized_key for "{{ username }}"
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', ansible_ssh_private_key_file ~ '.pub') }}"
