- name: Install nodejs
  include_role:
    name: asdf
  vars:
    asdf_skip_update: True
    asdf_plugins:
      - name: "nodejs"
        repository: "https://github.com/asdf-vm/asdf-nodejs.git"
        versions:
          - "latest"
        global: "latest"

- name: Install/Update pnpm
  become_user: "{{ username }}"
  community.general.npm:
    name: pnpm
    state: latest
    global: true
