- name: Install Starship
  block:
    - name: Remove old binary
      become_user: "{{ username }}"
      file:
        path: "$STARSHIP_HOME"
        state: absent

    - name: Create folders
      become_user: "{{ username }}"
      file:
        path: "$STARSHIP_HOME"
        state: directory
        recurse: yes

    - name: Download Installer
      get_url:
        url: https://starship.rs/install.sh
        owner: "{{ username }}"
        mode: "u+rx"
        dest: /tmp/starship.sh

    - name: Run Installer
      become_user: "{{ username }}"
      command: "/tmp/starship.sh -b $STARSHIP_HOME -y"

- name: Install fonts
  block:
    - name: Create directories
      become_user: "{{ username }}"
      file:
        state: directory
        path: "{{ item }}"
        recurse: yes
      with_items:
        - "{{ base_directory}}/ryanoasis/nerd-fonts"

    - name: Clone repository
      become_user: "{{ username }}"
      git:
        repo: "https://github.com/ryanoasis/nerd-fonts.git"
        dest: "{{ base_directory}}/ryanoasis/nerd-fonts"
        depth: 1

    - name: Run installer
      command: ./install.sh
      become_user: "{{ username }}"
      args:
        chdir: "{{ base_directory}}/ryanoasis/nerd-fonts"
