- name: Install deno
  include_role:
    name: asdf
  vars:
    asdf_skip_update: True
    asdf_plugins:
      - name: "deno"
        repository: "https://github.com/asdf-community/asdf-deno.git"
        versions:
          - "latest"
        global: "latest"
