- include_tasks: arch.yml

- name: Include OS-specific variables
  include_vars: "{{ lsb_base_id }}.yml"

- name: Install dependencies
  package:
    state: present
    name: "{{ docker_deps }}"

- name: Install Docker (Ubuntu)
  when: lsb_base_id == 'Ubuntu'
  block:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch={{ repo_arch }}] https://download.docker.com/linux/{{ lsb_base_id | lower }} {{ lsb_base_codename }} stable"
        state: present

- name: Update and upgrade apt packages
  when: ansible_facts['os_family'] == 'Debian'
  apt:
    update_cache: yes
    name: "{{ docker_packages }}"
    state: present

- name: Ensure group docker exists
  group:
    name: docker
    state: present

- name: Add user "{{ username }}" to group docker
  user:
    name: "{{ username }}"
    groups:
      - docker
    append: yes

- name: Prune everything (including non-dangling images)
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true

- name: homeserver tasks
  when: ansible_facts['hostname'] != "localhost"
  block:
    - name: Create general docker network
      community.docker.docker_network:
        name: docker_network
        state: present
        force: yes
        ipam_config:
          - subnet: 172.20.0.0/24
