- name: Stop all containers safely
  block:
    - name: Get a list of all running containers
      docker_host_info:
        containers: true
      register: docker_info
    - name: Stop all running containers
      docker_container:
        name: '{{ item.Names[0] | regex_replace("^/", "") }}'
        state: stopped
      loop: "{{ docker_info.containers }}"

- name: Prune everything (including non-dangling images)
  community.docker.docker_prune:
    containers: true
    images: true
    images_filters:
      dangling: false
    networks: true
    volumes: true
    builder_cache: true

- name: Create general docker network
  when:
    - docker_generate_network | default(False) == True
  block:
    - name: Enable experimental requirements for IPv6
      copy:
        dest: /etc/docker/daemon.json
        content: "{{ docker_json }}"
      vars:
        docker_json: {
          "ip6tables": true,
          "experimental": true,
          "userland-proxy": false
        }
    - name: Configure proxy_network network
      community.docker.docker_network:
        name: proxy_network
        state: present
        force: yes
        enable_ipv6: yes
        ipam_config:
          - subnet: "172.20.0.0/24"
          - subnet: "fd00:cafe:face:feed::/64"

    - name: Restart docker daemon
      service:
        name: docker
        state: restarted
        enabled: yes

- name: Stop all containers every day at 4:40 AM
  when:
    - docker_stop_containers | default(False) == True
  cron:
    name: "Stop all containers every day at 4:40 AM"
    minute: "40"
    hour: "4"
    job: "docker stop $(docker container ls -q)"
