- include_vars: traefik.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "traefik:v3"
    pull: yes
    state: "started"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
      "CF_DNS_API_TOKEN": "{{ cf_token }}"
    ports: "{{ host_port }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ docker_dir }}/{{ container_name }}/letsencrypt:/letsencrypt"
    command:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.cloudflare.acme.email=breno-salles@hotmail.com"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json"
      - "--log.level=DEBUG"
      - "--providers.docker.network=reverse_proxy"
    networks:
      - name: reverse_proxy
    comparisons:
      networks: strict
    etc_hosts:
      "host.docker.internal": "host-gateway"
    restart_policy: always
    labels:
      "traefik.enable": "true"
      "traefik.docker.network": "reverse_proxy"
      "traefik.http.services.traefik.loadbalancer.server.port": "8080"

      "traefik.http.routers.traefik.rule": "Host(`{{ domains.base.domain }}`)"
      "traefik.http.routers.traefik.tls": "true"
      "traefik.http.routers.traefik.entrypoints": "websecure"
      "traefik.http.routers.traefik.tls.certresolver": "cloudflare"
      "traefik.http.routers.traefik.middlewares": "basic-auth"

      "traefik.http.middlewares.basic-auth.basicauth.users": "guergeiro:{{ user_hashed_password }}"


- name: Start {{ container_name }} at 5:00 AM
  cron:
    name: "Start {{ container_name }} at 5:00 AM"
    minute: "0"
    hour: "5"
    job: "docker start {{ container_name }}"
