- name: Install required packages
  package:
    name:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
      - python3
    state: present

- name: check if alacritty is installed
  command: alacritty --version
  register: alacritty_exists
  become_user: "{{ username }}"
  ignore_errors: yes

- name: Prepare folders
  when: alacritty_exists is failed
  block:
    - name: Remove old binary
      become_user: "{{ username }}"
      file:
        path: "$ALACRITTY_HOME"
        state: absent

    - name: Create folders
      become_user: "{{ username }}"
      file:
        path: "$ALACRITTY_HOME"
        state: directory
        recurse: yes

- name: Install alacritty
  become_user: "{{ username }}"
  community.general.cargo:
    name: alacritty
    state: latest
    path: "$ALACRITTY_HOME"

- name: Create the directory
  become_user: "{{ username }}"
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
  with_items:
    - "{{ base_directory}}/dracula/alacritty"
    - "{{ base_directory}}/ryanoasis/nerd-fonts"

- name: Clone repository
  become_user: "{{ username }}"
  git:
    repo: "{{ item.url }}"
    dest: "{{ item.directory }}"
    depth: 1
  with_items:
    - {
        directory: "{{ base_directory}}/dracula/alacritty",
        url: "https://github.com/dracula/alacritty.git",
      }
    - {
        directory: "{{ base_directory}}/ryanoasis/nerd-fonts",
        url: "https://github.com/ryanoasis/nerd-fonts.git",
      }

- name: Install fonts
  command: ./install.sh
  become_user: "{{ username }}"
  args:
    chdir: "{{ base_directory}}/ryanoasis/nerd-fonts"
