- include_tasks: mosquitto.yml
- include_tasks: zigbee2mqtt.yml
- include_tasks: signal-messenger.yml
  when:
    - homeassistant_signal | default(False) == True
- include_tasks: music-assistant.yml
- include_tasks: homeassistant.yml
