- include_vars: music-assistant.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/data"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/music-assistant/server:latest"
    pull: yes
    state: "started"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
    exposed_ports:
      - 8095
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/data"
    network_mode: "host"
    restart_policy: always

- name: Start {{ container_name }} at 5:00 AM
  cron:
    name: "Start {{ container_name }} at 5:00 AM"
    minute: "0"
    hour: "5"
    job: "docker start {{ container_name }}"
