- include_vars: zigbee2mqtt.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/data"

- name: Copy the config file
  copy:
    src: files/zigbee2mqtt/
    dest: "{{ docker_dir }}/{{ container_name }}/data/"
    decrypt: yes
    owner: "root"
    group: "root"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "koenkk/zigbee2mqtt:latest"
    pull: yes
    state: "started"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/app/data"
      - "/run/udev:/run/udev:ro"
    devices:
      - "/dev/serial/by-id/{{ zigbee_coordinator_id }}:/dev/ttyACM0"
    networks:
      - name: docker_network
    purge_networks: yes
    restart_policy: always

- name: Start {{ container_name }} at 5:00 AM
  cron:
    name: "Start {{ container_name }} at 5:00 AM"
    minute: "0"
    hour: "5"
    job: "docker start {{ container_name }}"
