- include_vars: zigbee2mqtt.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}/data"

- name: Copy the config file
  copy:
    src: "files/{{ ansible_facts['hostname'] }}/zigbee2mqtt/"
    dest: "{{ docker_dir }}/{{ container_name }}/data/"
    decrypt: yes
    owner: "root"
    group: "root"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "koenkk/zigbee2mqtt:latest"
    pull: yes
    state: "started"
    recreate: yes
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}/data:/app/data"
      - "/run/udev:/run/udev:ro"
    devices:
      - "/dev/serial/by-id/{{ zigbee_coordinator_id }}:/dev/ttyACM0"
    networks:
      - name: docker_network
    restart_policy: always
    labels:
      "traefik.enable": "true"
      "traefik.http.services.zigbee2mqtt.loadbalancer.server.port": "8080"

      "traefik.http.routers.zigbee2mqtt.rule": "Host(`{{ domains.zigbee2mqtt.domain }}`)"
      "traefik.http.routers.zigbee2mqtt.entrypoints": "websecure"
      "traefik.http.routers.zigbee2mqtt.tls": "true"
      "traefik.http.routers.zigbee2mqtt.tls.certresolver": "cloudflare"
      "traefik.http.routers.zigbee2mqtt.middlewares": "basic-auth"

- name: Start {{ container_name }} at 5:00 AM
  cron:
    name: "Start {{ container_name }} at 5:00 AM"
    minute: "0"
    hour: "5"
    job: "docker start {{ container_name }}"
