- include_tasks: postgres.yml
- include_tasks: vaultwarden.yml
- include_tasks: redis.yml
- include_tasks: tika.yml
- include_tasks: gotenberg.yml
- include_tasks: paperless.yml
- include_tasks: homeassistant.yml
- include_tasks: mosquitto.yml
- include_tasks: zigbee2mqtt.yml
