- name: Remove old binary
  become_user: "{{ username }}"
  file:
    path: "$NEOVIM_HOME"
    state: absent

- name: Create folders
  become_user: "{{ username }}"
  file:
    path: "$NEOVIM_HOME"
    state: directory
    recurse: yes

- name: Download binary
  become_user: "{{ username }}"
  unarchive:
    src: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    dest: "$NEOVIM_HOME"
    remote_src: yes
