- include_vars: wireguard.yml

- name: Create the directories
  file:
    state: directory
    path: "{{ item }}"
    recurse: yes
    owner: "root"
    group: "root"
  with_items:
      - "{{ docker_dir }}/{{ container_name }}"

- name: Make sure the {{ container_name }} container is created and running
  community.docker.docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/wg-easy/wg-easy:latest"
    pull: yes
    state: "started"
    recreate: yes
    capabilities:
      - net_admin
      - sys_module
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    env:
      "WG_HOST": "{{ wireguard_hostname }}"
      "TZ": "{{ timezone }}"
      "WG_DEVICE": "{{ wireguard_inet_interface }}"
      "WG_DEFAULT_ADDRESS": "10.8.0.x"
    ports: "{{ host_port }}"
    volumes:
      - "{{ docker_dir }}/{{ container_name }}:/etc/wireguard"
    networks:
      - name: docker_network
    restart_policy: always

- name: Start {{ container_name }} at 5:00 AM
  cron:
    name: "Start {{ container_name }} at 5:00 AM"
    minute: "0"
    hour: "5"
    job: "docker start {{ container_name }}"
